Correct first installation command: substitute deprecated nvidia-docker
NVIDIA/TensorRT-LLM pull request #1096
Opened 2024-02-17 14:46 UTC by HeAndres

"nvidia-docker run" was replaced by "docker run --rm --runtime=nvidia --gpus all"

2024-02-21 08:33 UTC, HeAndres commented
The corrected first command can be seen in the [docs](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/sample-workload.html) for Nvidia Container Toolkit. Installation of NCT is a pre-requisite, as written in the Installation section of the [Readme.md](https://github.com/NVIDIA/TensorRT-LLM/blob/main/README.md).

2024-02-22 07:30 UTC, Shixiaowei02 commented
Thanks for the suggestion, we will fix this issue.

2024-02-22 07:34 UTC, HeAndres commented
I would like to contribute if it is possible. Could you tell me further steps to make a successful PR, or any thing that you need to make this PR successful? Thank you in advance!

2024-02-22 07:41 UTC, Shixiaowei02 requested changes

2024-02-22 07:41 UTC, Shixiaowei02 commented on README.md
>  # Please use the `nvidia-docker` application, using only `docker` may cause exceptions.
```suggestion
```

2024-02-22 07:41 UTC, Shixiaowei02 commented on README.md
>  # Please use the `nvidia-docker` application, using only `docker` may cause exceptions.
Please delete this sentence. Thanks!

2024-02-22 07:46 UTC, Shixiaowei02 approved these changes

2024-02-22 07:47 UTC, Shixiaowei02 commented
> I would like to contribute if it is possible. Could you tell me further steps to make a successful PR, or any thing that you need to make this PR successful? Thank you in advance!

Thank you for your contribution, please wait for the code to be merged.

2024-02-26 03:08 UTC, merged